#!/usr/bin/python3
# filename : ref
# author : draeician (July 22, 2023)
# purpose : to allow for fast cli recording from the command line for later reference

import os
import re
import sys
import requests
import argparse
import warnings
from datetime import date
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from urllib.parse import urlparse
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

import urllib3
import chardet
import charset_normalizer

urllib3.__version__ = '2.0.4'
chardet.__version__ = '5.2.0'
charset_normalizer.__version__ = '3.2.0'


__VERSION__ = "v1.3.1"

# Filter out the RequestsDependencyWarning
warnings.filterwarnings("ignore", category=DeprecationWarning, module="urllib3")

# Adjust the following line to point to the actual location of your .env file
env_path = os.path.join(os.path.expanduser("~"), '.env')
load_dotenv(dotenv_path=env_path)
#load_dotenv()

YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'

# Check for yt api key - offer to set if None
from dotenv import set_key
def set_developer_key():
    key = input("Please enter your YOUTUBE_API_KEY: ")
    os.environ['YOUTUBE_API_KEY'] = key
#`    env_path = os.path.join(BASE, '.env') # Modify this to point to your .env file
    set_key(env_path, 'YOUTUBE_API_KEY', key)
    print("YOUTUBE_API_KEY set successfully!")

DEVELOPER_KEY = os.getenv('YOUTUBE_API_KEY')

if DEVELOPER_KEY is None:
    print('Error: YOUTUBE_API_KEY is not set in .env file or shell environment.')
    choice = input('Would you like to set it now? (yes/no): ')

    if choice.lower() == 'yes':
        set_developer_key()
else:
    # print if debug is set
    if os.getenv('DEBUG') == 'True':
        print('YOUTUBE_API_KEY is set.')

# Replace with the user's home directory
BASE = os.path.expanduser("~/")

YOUTUBE = os.path.join(BASE, "references", "youtube_references.md")
LINKS = os.path.join(BASE, "references", "links.md")

def get_youtube_data(url: str) -> tuple:
    youtube = build(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION, developerKey=DEVELOPER_KEY)
    video_id = urlparse(url).query.split('v=')[-1]
    video_response = youtube.videos().list(part='snippet', id=video_id).execute()
    video_data = video_response['items'][0]['snippet']
    return video_id, video_data['title'], video_data['channelTitle']

def ensure_path_exists(file_path: str):
    directory = os.path.dirname(file_path)
    if not os.path.exists(directory):
        os.makedirs(directory)
    if not os.path.exists(file_path):
        open(file_path, 'w').close()

def append_to_file(file_path: str, line: str) -> None:
    ensure_path_exists(file_path)
    with open(file_path, "a") as f:
        f.write(line)
        f.flush()
        os.fsync(f.fileno())

# took a stab at jiggering this around so that --edit is a special case and we don't process the url instead
def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Add URL to markdown files.")
    parser.add_argument("url", nargs='?', default=None, help="URL to be added.")
    parser.add_argument("-f", "--force", action="store_true", help="Force addition even if URL already exists.")
    parser.add_argument("-e", "--edit", action="store_true", help="Open markdown file for editing.")
    parser.add_argument("-d", "--debug", action="store_true", help="Print debug information.")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__VERSION__}") 
    args = parser.parse_args()

    if args.edit:
        if args.url and "www.youtube.com" in args.url:
            os.system(f"vim {YOUTUBE}")
            sys.exit()
        else:
            os.system(f"vim {LINKS}")
            sys.exit()

    if args.url:
        args.url = args.url.replace('&', '\&')

    return args

def url_exists_in_file(url: str, file_path: str) -> bool:
    with open(file_path, "r") as f:
        for line in f:
            urls = re.findall(r'\[([^\]]+)\]', line)
            for url_str in urls:
                extracted_url = url_str.split(']')[0]
                if url == extracted_url:
                    return True
    return False

def get_channel_name(url: str) -> str:
    parsed_url = urlparse(url)
    channel_path = parsed_url.path.rstrip('/')
    channel_name = channel_path.split('/')[-1]
    return channel_name

def get_title_from_url(url: str) -> str:
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36'
    }
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            soup = BeautifulSoup(response.content, 'html.parser')
            title = soup.title.string.strip() if soup.title and soup.title.string else "No title found"
            return title
        else:
            return f"Failed to fetch page content (status code: {response.status_code})"
    except Exception as e:
        return f"Error fetching title: {str(e)}"

def process_url(url: str, force: bool) -> None:
    if "youtube.com" in url:
        channel_id = re.search(r"/(user|channel)/([\w-]+)", url)
        if channel_id:
            channel_id = channel_id.group(2)
            channel_url = f"https://www.youtube.com/{channel_id}"
            if url_exists_in_file(channel_url, YOUTUBE):
                print(f"Error: Channel URL {channel_url} already recorded.")
            else:
                channel_name = get_channel_name(channel_url)
                if channel_name:
                    append_to_file(YOUTUBE, f"{date.today()}|[{channel_url}]|Youtube Creator {channel_name}\n")
                    print(f"{date.today()}|[{channel_url}]|Youtube Creator {channel_name}")
                else:
                    print("Invalid YouTube Channel URL")
        else:
            video_id, title, uploader = get_youtube_data(url)
            if video_id and title and uploader:
                title = re.sub('[^0-9a-zA-Z]+', ' ', title)
                title = " ".join(title.split())
                video_url = f"https://www.youtube.com/watch?v={video_id}"
                if url_exists_in_file(video_url, YOUTUBE):
                    print(f"Error: Video URL {video_url} already recorded.")
                else:
                    append_to_file(YOUTUBE, f"{date.today()}|[{video_url}]|({title})|{uploader}\n")
                    print(f"{date.today()}|[{video_url}]|({title})|{uploader}")
            else:
                print("Invalid YouTube URL")
    else:
        title = get_title_from_url(url)
        if title and not title.startswith("Error"):
            if url_exists_in_file(url, LINKS):
                print(f"Error: URL {url} already recorded.")
            else:
                append_to_file(LINKS, f"{date.today()}|[{url}]|({title})\n")
                print(f"{date.today()}|[{url}]|({title})")
        else:
            print("Invalid URL")

def main() -> None:
    ensure_path_exists(YOUTUBE)
    ensure_path_exists(LINKS)
    try:
        args = parse_arguments()
        if args.url:
            process_url(args.url, args.force)
        else:
            while True:
                try:
                    url = input("Enter a URL to record (or press Ctrl+C to quit): ")
                    force = False
                    process_url(url, force)
                except Exception as e:
                    print(f"An error occurred: {e}")
    except KeyboardInterrupt:
        print("\nExiting...")
        sys.exit(0)

if __name__ == "__main__":
    main()

